version: "3.8"

services:
  redis:
    image: 'redis:6.0'
    container_name: redis-demo
    ports:
      - '63379:6379'
    volumes:
      - redis-data:/var/lib/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mysql:
    image: mysql:8.0
    container_name: mysql-demo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: congpham
      MYSQL_DATABASE: demo

volumes:
  mysql-data:
  redis-data:

networks:
  esnet: